---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: waverx-vision
spec:
  replicas: 1
  selector:
    name: waverx-vision
  template:
    metadata:
      labels:
        name: waverx-vision
    spec:
      containers:
        - image: quay.io/olagoldhackxx/waverx-vision:v1
          name: waverx-vision
          ports:
            - containerPort: 9001
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
            - mountPath: /opt/models
              name: waverx-vision
      volumes:
        - name: waverx-vision
          persistentVolumeClaim:
            claimName: waverx-vision