apiVersion: v1

kind: PersistentVolumeClaim

metadata:

  name: waverx-vision

spec:

  resources:

    requests:

      storage: 5Gi

  volumeMode: Filesystem

  accessModes:

    - ReadWriteOnce
